### ISSUE TITLE
DefaultEncoder.canonicalize() does not properly decode percent-encoded values.

### ISSUE THREAD

**Issue by xeno6696** [ESAPI/esapi-java#1]
Junit test:

```
    @Test
    public void testESAPIPercentEncoding() {
        String input = "%E2%84%A2";
        String expected = "™";
        Encoder e = ESAPI.encoder();
        assertEquals(expected, e.canonicalize(input));
    }
```

**Comment by kadary** [comment]
Hello,
I think this issue should be move to esapi-java-legacy (version 2.x) issue tracker. This repository is ESAPI version 3.x project which is under development. Just close this issue and open a new one in https://github.com/ESAPI/esapi-java-legacy/issues for ESAPI team to be able to fix it

**Comment by kwwall** [comment]
Just noticed this again @xeno6696 -- Did you open this issue for ESAPI/esapi-java-legacy? If so, I will close it here.
Thanks,
-kevin

**Comment by xeno6696** [comment]
This one was opened against the wrong project.
