### ISSUE TITLE
com.ibm.uvm.tools unresolved

### ISSUE THREAD

**Issue by dsearles-celerium** [ESAPI/esapi-java#12]
When I add **esapi-2.2.3.0.jar** to my OSGI project, the bundle will not load due to an unresolved reference to **com.ibm.uvm.tools**. Is there a circumvention for this so I can use ESAPI in my project?

**Comment by dsearles-celerium** [comment]
Posted to wrong project, needs to be in ESAPI Legacy

**Comment by kwwall** [comment]
@dsearles-celerium - Can you move this to the GitHub issue for esapi-java-legacy. I.e.,
https://github.com/ESAPI/esapi-java-legacy/issues, and then we can discuss it?

Or better, post to the ESAPI-Users mailing list as discussed in https://github.com/ESAPI/esapi-java-legacy/blob/develop/README.md. I don't think this is an ESAPI bug as the only reference to any **com.ibm** package name space is in `SecurityProviderLoader` class, where this like is called:
```
        jceProviders.put("IBMJCE", "com.ibm.crypto.provider.IBMJCE");
```
