### ISSUE TITLE
ESAPI life status

### ISSUE THREAD

**Issue by grtessman** [ESAPI/esapi-java#8]
Hey guys, is ESAPI 2.0 officially dead now?  What's the status on version 3.0 - word on the street is that this is dead and isn't really maintained anymore.  Being asked to move away from it now.

**Comment by jackycct** [comment]
I have asked the same in Dec last year. Kevin W. Wall mentioned that the contributors are still contributing to 2.x. 
There is no timeline for 3.0.

**Comment by xeno6696** [comment]
ESAPI 2.x is not dead, but it IS limping.  It's pretty much everything that 3 people can do to just keep *any* progress moving on that project.  We could always use a helping hand.  

As far as 3.x, we've had a couple of small discussions, but, see above.

**Comment by jackycct** [comment]
@xeno6696 Happy to start helping out (after worldcup :))

**Comment by kwwall** [comment]
I think this should be closed. Doesn't belong in the repo anyhow.
